bloghub/urls.py
from django.conf.urls.defaults import patterns, include, url
from bloghub.blog.views import *
from django.views.generic.simple import direct_to_template
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import os.path
from django.views.generic import FormView
from blog.forms import BlogPostSaveForm
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

# site_media = os.path.join(os.path.dirname(__file__), 'site_media').replace('\\', '/')
# site_media = "C:/djcode/bloghub/site_media"

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'bloghub.views.home', name='home'),
    # url(r'^bloghub/', include('bloghub.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    # Browsing
    (r'^$', main_page),
    url(r'^user/(\w+)/$', user_page, name="user_page"),
    url(r'^user/(\w+)/draft/$', draft_page, name="draft_page"),
    (r'^tag/([^\s]+)/$', tag_page),
    # (r'^tag/$', tag_cloud_page),
    (r'^search/$', search_page),
    url(r'^blogpost/(\d+)/$', blogpost_detail_page, name="blogpost_detail"),
    url(r'^draft/(\d+)/$', draft_detail_page, name="draft_detail"),
    # Session management
    url(r'^accounts/login/$', login_page, name="login_page"),
    url(r'^accounts/logout/$', logout_page, name="logout_page"),
    # (r'^site_media/(?P<path>.*)$', 'django.views.static.server',
    #     { 'document_root':site_media }),
    # (r'^site_media/css/(?P<path>.*)$', 'django.views.static.server',
    #     { 'document_root':site_media + '/css/' }),
    # (r'^site_media/js/(?P<path>.*)$', 'django.views.static.server',
    #     { 'document_root':site_media + '/js/' }),
    # (r'^site_media/img/(?P<path>.*)$', 'django.views.static.server',
    #     { 'document_root':site_media + '/img/' }),               
    url(r'^register/$', register_page, name="register_page"),
    (r'^register/success/$', direct_to_template,
        { 'template': 'registration/register_success.html' }),
    # Account management
    url(r'^save/$', blogpost_save_page, name="blogpost_save"),
    url(r'^blogpost/edit/(\d+)/$', blogpost_save_page, name="blogpost_update"),
    url(r'^blogpost/delete/(\d+)/$', blogpost_delete, name="blogpost_delete"),
    # url(r'^blogpost/delete/$', blogpost_delete, name="blogpost_delete"),
    # if there is no parameters from security respect? 
    # url(r'^blogpost/edit/$', blogpost_save_page, name="blogpost_update"),
    # Friends
    (r'^following/(\w+)/$', friends_page),
    (r'^friend/add/$', friend_add),
    (r'^friend/remove/$', friend_remove),
    # django comments
    (r'^comments/', include('django.contrib.comments.urls')),
    (r'^ratings/', include('ratings.urls')),
    (r'^ajax/tag/autocomplete/$', ajax_tag_autocomplete),
    url(r'^$', FormView.as_view(
        template_name="blogpost_detail.html",
        form_class=BlogPostSaveForm)),
)
urlpatterns += staticfiles_urlpatterns()
urlpatterns += patterns('',
    url(r'^wechat/',include('wechat.urls')),
)

bloghub/blog/models.py
# coding: UTF-8
from django.contrib.auth.models import User
from django.db import models

# class Profile(models.Model):
# 	user = models.OneToOneField(User)
# 	avatar = models.ImageField()
# 	name = models.CharField()
# 	description = models.TextField()

class BlogPost(models.Model):
	LIVE_STATUS = 1
	DRAFT_STATUS = 2
	STATUS_CHOICES = (
		(LIVE_STATUS, 'Live'),
		(DRAFT_STATUS, 'Draft'),
	)
	title = models.CharField(max_length=150)
	body = models.TextField()
    # timestamp = models.DateTimeField()
	user = models.ForeignKey(User)
	status = models.IntegerField(choices=STATUS_CHOICES, default=LIVE_STATUS)
	def __str__(self):
		return '%s, %s' % (self.user.username, self.title)

class Collection(models.Model):
	name = models.CharField(max_length=150, unique=True)
	desc = models.TextField()
	user = models.ForeignKey(User)
	def __str__(self):
		return '%s, %s' % (self.user.username, self.name)

class Tag(models.Model):
    name = models.CharField(max_length=64, unique=True)
    blogposts = models.ManyToManyField(BlogPost)
    collections = models.ManyToManyField(Collection)
    def __str__(self):
        return self.name

class Followingship(models.Model):
	following = models.ForeignKey(
		User, related_name='following_set'
		)
	followers = models.ForeignKey(
		User, related_name='followers_set')
	def __unicode__(self):
		return u'%s, %s' % (self.following.username,
			self.followers.username)
	class Meta:
		unique_together = (('followers', 'following'), )

bloghub/rating/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic

CHOICES=(
    ('1', 'Bullshit'),
    ('2', 'Just so so'),
    ('3', 'Copied'),
    ('4', 'Help me a lot'),
    ('5', 'Awesome! Recommend!'),
    )
class Rating(models.Model):
	content_type = models.ForeignKey(ContentType)
	object_id = models.IntegerField()
	content_object = generic.GenericForeignKey('content_type', 'object_id')
	score = models.PositiveSmallIntegerField(choices=CHOICES)
	user = models.ForeignKey(User)

bloghub/blog/forms.py
import re
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django import forms
from pagedown.widgets import PagedownWidget

class RegistrationForm(forms.Form):
    username = forms.CharField(label='Username', max_length=20)
    email = forms.EmailField(label='Email')
    password1 = forms.CharField(
        label = 'Password',
        widget=forms.PasswordInput()
    )
    password2 = forms.CharField(
        label = 'Password (Again)',
        widget=forms.PasswordInput()
    )

    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 == password2:
                return password2
        raise forms.ValidationError('Passwords do not match.')
    
    def clean_username(self):
        username = self.cleaned_data['username']
        if not re.search(r'^\w+$', username):
            raise forms.ValidationError('Username can only contain\
            alphanumeric characters and the underscore.')
        try:
            User.objects.get(username=username)
        except ObjectDoesNotExist:
            return username
        raise forms.ValidationError('Username is already taken.')

class BlogPostSaveForm(forms.Form):
    title = forms.CharField(
        # label = 'Title',
        widget = forms.TextInput(attrs={'size': 128}))
    body = forms.CharField(
        # label='Post', 
        # widget=forms.Textarea())
        widget=PagedownWidget())
    tags = forms.CharField(
        # label='Tags',
        required = True,
        widget = forms.TextInput(attrs={'rows': 3}))

class SearchForm(forms.Form):
    query = forms.CharField(
        label=u'Search for',
        widget=forms.TextInput(attrs={'size':32})
        )

bloghub/rating/forms.py
import re
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django import forms

CHOICES=(
    ('1', 'Bullshit'),
    ('2', 'Just so so'),
    ('3', 'Copied'),
    ('4', 'Help me a lot'),
    ('5', 'Awesome! Recommend!'),
    )

class AddRateForm(forms.Form):
    score = forms.IntegerField(widget=forms.RadioSelect, choice=CHOICES)

bloghub/rating/views.py
from ContentType.contents.models import *
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render_to_response, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import logout, login, authenticate
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.db import models
from rating.models import *
from rating.forms import *
import pdb

#pdb.set_trace()
@login_required
def add_rate(request):
	if request.method == 'POST':
		data = request.POST.copy()
		ctype = data.get("content_type")
		object_pk = data.get("object_pk")
		form = AddRateForm(request.POST)
		if form.is_valid():
			score = form.cleaned_data['score']
    		content_object = ContentType.objects.get(pk=ctype.pk).get_object_for_this_type(pk=object_pk)
			rating = Rating.objects.get_or_create(content_object=content_object, score=score, rater=request.user)
			rating.save()
			return HttpResponseRedirect('.')
	else:
		form = AddRateForm()
	variables = RequestContext(request, {
        'form':form
        })
	return render_to_response('rating/rating.html', variables)

bloghub/templates/blogpost_detail.html
{% extends "base.html" %}
{% block title %}{{ blogpost.title }}{% endblock %}
{% block head %}{{ blogpost.title }}{% endblock %}
{% load markup %}
{% block content %}
  {{ blogpost.body|markdown|safe }}
  {% if show_tags %}
    {% if blogpost.tag_set.all %}
      <div class="post-tags">
        {% for tag in blogpost.tag_set.all %}
          <div class="post-tag">
            #<a class="post-tag" href="/tag/{{ tag.name|urlencode }}/">{{ tag.name }}</a>
          </div>
        {% endfor %}
      </div>
    {% else %}
    {% endif %}
  {% endif %}
  {% if show_edit %}
    <div class="post-controls">
      <button href="{% url blogpost_update blogpost.id %}" class="post tool edit">edit</button>
    <!-- </div>
    <div class="post-controls"> -->
      <form onsubmit="return confirm('Are you sure you want to delete this post?')" method="post" action="{% url blogpost_delete blogpost.id %}">
        <input type="hidden" value="{{ blogpost.id }}" name="id">
        <button class="post tool delete">delete</button>
        <!-- <a href="{% url blogpost_delete blogpost.id %}" class="post tool delete" onclick="return confirm('Are you sure you want to delete this post?')">[delete]</a> -->
      </form>
    </div>
  {% endif %}
  {% if user.id == blogpost.user_id%}
    {% include "ratings.html" %}
    <!-- <p>You cannot rate your own blog</p> -->
  {% else %}
    {% include "ratings.html" %}
    {% include "ratings_form.html" %}
  {% endif %}
  {% include "comments/comments.html" %}
  {% include "comments/comment_form.html" %}
{% endblock %}

bloghub/templates/blogpost_list.html
<script src="{{ STATIC_URL }}js/delete.js"></script>
{% load markup %}
{% if blogposts %}
  <div class="post-bucket">
    {% for blogpost in blogposts %}
      <div class="post-item">
        <h2 class="post-item-title">
        <a href="/blogpost/{{ blogpost.id }}" class="title">{{ blogpost.title }}</a></h2>
        <div class="row">
          <div class="span9">
            {% if show_user %}
              Posted by:  
              <a href="/user/{{ blogpost.user.username }}/" class="username">
              {{ blogpost.user.username }}</a>
            {% endif %}
          </div>
          <div class="span9">
            {% if show_edit %}
            <!-- <a href="/save/?id={{ blogpost.id|urlencode }}" class="edit">[edit]</a> -->
              <div class="post-controls">
                <a href="{% url blogpost_update blogpost.id %}" class="post tool edit">[edit]</a>
              </div>
              <div class="post-controls">
                <a id="{{blogpost.id}}" href="javascript:void(0)" class="post tool delete">[delete]</a>
              </div>
            {% endif %}
          </div>
        </div>
        {% if show_body %}
          {{ blogpost.body|markdown|safe|truncatewords_html:20 }}<a href="/blogpost/{{ blogpost.id }}">Read more...</a>
        {% endif%}
        <br />
        {% if show_tags %}
          {% if blogpost.tag_set.all %}
            <div class="post-tags">
              {% for tag in blogpost.tag_set.all %}
                <div class="post-tag">
                  #<a class="post-tag" href="/tag/{{ tag.name|urlencode }}/">{{ tag.name }}</a>
                </div>
              {% endfor %}
            </div>
          {% else %}
          {% endif %}
        {% endif %}
      <hr />
      </div>
    {% endfor %}
  </div>
{% else %}
  <p>No blog posts found.</p>
{% endif %}

bloghub/templates/blogpost_save-old.html
{% extends "base.html" %}
{% block external %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/jquery.ui.autocomplete.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/jquery.tagsinput.css">
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.ui.autocomplete.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}tiny_mce/tiny_mce.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.tagsinput.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/tag_autocomplete.js"></script>
    <script type="text/javascript">
    tinyMCE.init({
        mode: "textareas",
        theme: "advanced",
        theme_advanced_resizing : true
    });
    $('#tags').tagsInput();
    </script>
{% endblock %}
{% block title %}Save blog post{% endblock %}
{% block head %}Save blog post{% endblock %}
{% block subhead %}Express your interest{% endblock %}
{% block content %}

<form class="form-horizontal" method="post" action=".">
	<div class="control-group">
		<label class="control-label" for="id_username">Title:</label>
    		<div class="controls">
    			{{ form.title }}
    		</div>
    </div>
    <div class="control-group">
		<label class="control-label" for="id_post">Post:</label>
			<div class="controls">
				{{ form.body }}
    		</div>
    </div>
    <div class="control-group">
        <label class="control-label" for="id_tag">Tag:</label>
            <div class="controls">
                {{ form.tags }}
                <!-- <input type="text" name="tags" placeholder="Tags" class="tm-input"/> -->
            </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <button type="submit" class="btn btn-success">Submit</button>
            <button type="submit" class="btn btn-warning">Save as draft</button>
        </div>
    </div>
    <!-- <input type="submit" value="save" /> -->
</form>
{% endblock %}

bloghub/templates/blogpost_save.html
{% extends "base.html" %}
{% block external %}
    {{ form.media }}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/jquery.ui.autocomplete.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}tagmanager/tagmanager.css">
    <!-- <link rel="stylesheet" href="{{ STATIC_URL }}jQuery-Tags-Input/jquery.tagsinput.css"> -->
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.ui.autocomplete.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}tagmanager/tagmanager.js"></script>
    <!--<script type="text/javascript" src="{{ STATIC_URL }}tiny_mce/tiny_mce.js"></script>-->
    <!--<script type="text/javascript" src="{{ STATIC_URL }}jQuery-Tags-Input/jquery.tagsinput.js"></script>-->
    <!--<script type="text/javascript" src="{{ STATIC_URL }}js/tag_autocomplete.js"></script>-->
    <script type="text/javascript">
        // jQuery(".tm-input").tagsManager();
    // tinyMCE.init({
    //     mode: "textareas",
    //     theme: "advanced",
    //     theme_advanced_resizing : true
    // });
    // $(document).ready(function(){
    //     // $('#tags').tagsInput();
    //     $('.tm-input').tagsManager({
    //          // hiddenTagListId: 'hidden_tags'
    //     });
    //     // $('#id_tags').tagsManager();
    //     // });
    //     $('#btn').click(function(){
    //         $('#tags').val($(':hidden_tags').val());
    //     });
    // });
        $(function(){
            $('.tm-input').tagsManager({
                // hiddenTagListId: 'hidden_tags'
            });
        });
        // $('button').click(function(){
        //     $('#tags').val($("[name='hidden-tags']").val());
        // });
    </script>
{% endblock %}
{% block title %}New shares{% endblock %}
{% block head %}Share new{% endblock %}
{% block subhead %}{% endblock %}
{% block content %}
<div class="shortcuts">
    <a href="/user/{{ user }}/" class="username">My posts</a>
    <a href="/user/{{ user }}/draft" class="username">My drafts</a>
</div>
<form class="form-horizontal" method="post" action=".">
    {% csrf_token %}
    {{ form.non_field_errors }}
	<div class="control-group">
    {{ form.title.errors }}
		<label class="control-label" for="id_username">Title:</label>
    		<div class="controls">
    			{{ form.title }}
    		</div>
    </div>
    <div class="control-group">
    {{ form.body.errors }}
		<label class="control-label" for="id_post">Post:</label>
			<div class="controls">
				{{ form.body }}
    		</div>
    </div>
    <div class="control-group">
    {{ form.tags.errors }}
        <label class="control-label" for="id_tag">Tag:</label>
            <div class="controls">
                <!-- {{ form.tags }} -->
                <input name="tags" id="tags" type="text" placeholder="Input tags..." class="tm-input" />
            </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <button name="submit_live" value="submit" type="submit" class="btn btn-success">Submit</button>
            <button name="submit_draft" value="save as draft" type="submit" class="btn btn-warning">Save as draft</button>
        </div>
    </div>
    <!-- <input type="submit" value="save" /> -->
</form>
{% endblock %}

bloghub/templates/draft_detail.html
{% extends "base.html" %}
{% block title %}{{ draft.title }}{% endblock %}
{% block head %}{{ draft.title }}{% endblock %}
{% block external %}
	<script src="{{ STATIC_URL }}js/publish.js"></script>
{% endblock %}
{% block content %}
	<p>{{ draft.body|safe }}</p>
	{% for tag in draft.tag_set.all %}
		<div class="post-tag">
			#<a class="post-tag" href="/tag/{{ tag.name|urlencode }}/">{{ tag.name }}</a>
		</div>
	{% endfor %}
	<div class="control-group">
        <div class="controls">
			<button action="/blogpost/{{ draft.id }}/" id="publish" name="submit_live" value="submit" type="submit" class="btn btn-success">Publish</button>
			<button name="back" value="back" type="submit" class="btn" onclick="goBack()" >Back</button>
			<a href="{% url blogpost_update draft.id %}" class="post-edit">[edit]</a>
		</div>
    </div>
{% endblock %}

bloghub/templates/draft_page.html
{% extends "base.html" %}
{% block title %}{{ username }}{% endblock %}
{% block head %}{{ username }}'s drafts{% endblock %}
{% block external %}<script src="{{ STATIC_URL }}js/follow.js"></script>{% endblock %}
{% block content %}
	{% include "draft_list.html" %}
{% endblock %}

bloghub/templates/friends_page.html
{% extends "base.html" %}
{% block title %}{{ username }}'s following{% endblock %}
{% block head %}{{ username }}'s following{% endblock %}
{% block content%}
  <h2>Following people</h2>
  {% if following_people %}
    <ul class="friends">
      {% for people in following_people %}
        <li><a href="/user/{{ people.username }}/">{{ people.username }}</a></li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No following people found.</p>
  {% endif %}
{% endblock %}
{% block rcontent %}
  
{% endblock %}

bloghub/templates/product_list.html
<script src="{{ STATIC_URL }}js/delete.js"></script>
{% load markup %}
{% if products %}
  <div class="post-bucket">
    {% for product in products %}
      <div class="span3">
        <div class="post-item">
          <h2 class="post-item-title">
          <a href="/wechat/product/{{ product.id }}" class="title">{{ product.name }}</a></h2>
          <div class="row">
            <div class="span9">
              {% if show_user %}
                Posted by:  
                <a href="/user/{{ product.user.username }}/" class="username">
                {{ product.user.username }}</a>
              {% endif %}
            </div>
            <div class="span9">
              {% if show_edit %}
              <!-- <a href="/save/?id={{ blogpost.id|urlencode }}" class="edit">[edit]</a> -->
                <div class="post-controls">
                  <a href="{% url blogpost_update blogpost.id %}" class="post tool edit">[edit]</a>
                </div>
                <div class="post-controls">
                  <a id="{{blogpost.id}}" href="javascript:void(0)" class="post tool delete">[delete]</a>
                </div>
              {% endif %}
            </div>
          </div>
          {% if show_body %}
            {{ product.desc|markdown|safe|truncatewords_html:20 }}<a href="/wechat/product/{{ product.id }}">Read more...</a>
          {% endif%}
          <br />
          <!-- {% if show_tags %}
            {% if blogpost.tag_set.all %}
              <div class="post-tags">
                {% for tag in blogpost.tag_set.all %}
                  <div class="post-tag">
                    #<a class="post-tag" href="/tag/{{ tag.name|urlencode }}/">{{ tag.name }}</a>
                  </div>
                {% endfor %}
              </div>
            {% else %}
            {% endif %}
          {% endif %} -->
        <hr />
        </div>
      </div>
    {% endfor %}
  </div>
{% else %}
  <p>No product found.</p>
{% endif %}

bloghub/templates/product_page.html
{% extends "base.html" %}
{% block title %}{{ username }}{% endblock %}
{% block head %}Products for {{ username }}{% endblock %}
{% block external %}
<script type="text/javascript">
  $(document).ready(function(){
    $("body").data("username", "{{username}}");
  });
</script>
<script src="{{ STATIC_URL }}js/follow.js"></script>{% endblock %}
{% block content %}
  {% include "product_list.html" %}
{% endblock %}
{% block rcontent %}
  {% ifequal user.username username %}
    <a href="/following/{{ username }}/">people you are following...</a>
    <a href="/tag-following/{{ username }}/">tags you are following...</a>
  {% else %}
    {% if is_following %}
      <a class="btn unfollow" href="javascript:void(0)">Unfollow</a>
    {% else %}
      <!-- <a class="btn icon follow" href="/friend/add/?username={{ username }}">Follow</a> -->
      <a class="btn btn-success follow" href="javascript:void(0)">Follow</a>
    {% endif %}
  {% endifequal %}
{% endblock %}

bloghub/templates/ratings.html
<h2>Review</h2>

{% load ratings_tags %}

{% get_rating_score for object as score %}
{% if score %}
    Average score: {{ score.average|floatformat }}
    Number of votes: {{ score.num_votes }}
{% else %}
    nobody voted
{% endif %}

bloghub/templates/search.html
{% extends "base.html" %}
{% block external %}
	<script type="text/javascript" src="{{ STATIC_URL }}search.js"></script>
{% endblock %}
{% block title %}Search BlogPosts{% endblock %}
{% block head %}Search BlogPosts{% endblock %}
{% block content %}
<form id="search-form" method="get" action=".">
	{{ form.as_p }}
	<input type="submit" value="search" />
</form>
<div id="search-results">
	{% if show_results %}
		{% include "blogpost_list.html" %}
	{% endif %}
</div>
{% endblock %}

bloghub/templates/tag_cloud_page.html
{% extends "base.html" %}
{% block title%}Tag Cloud{% endblock %}
{% block head %}Tag Cloud{% endblock %}
{% block content %}
	<div id="tag-cloud">
		{% for tag in tags %}
			<a href="/tag/{{ tag.name }}/"
				class="tag-cloud={{ tag.weight }}">
				{{ tag.name }}</a>
		{% endfor %}
	</div>
{% endblock %}

bloghub/templates/tag_page.html
{% extends "base.html"  %}
{% block title  %}Tag: {{ tag_name }}{% endblock %}
{% block head %}Blogposts for tag: {{ tag_name }}{% endblock %}
{% block content %}
  {% include "blogpost_list.html" %}
{% endblock  %}

bloghub/templates/user_page.html
{% extends "base.html" %}
{% block title %}{{ username }}{% endblock %}
{% block head %}Blog post for {{ username }}{% endblock %}
{% block external %}
<script type="text/javascript">
  $(document).ready(function(){
    $("body").data("username", "{{username}}");
  });
</script>
<script src="{{ STATIC_URL }}js/follow.js"></script>{% endblock %}
{% block content %}
  {% include "blogpost_list.html" %}
{% endblock %}
{% block rcontent %}
  {% ifequal user.username username %}
    <a href="/following/{{ username }}/">people you are following...</a>
    <a href="/tag-following/{{ username }}/">tags you are following...</a>
  {% else %}
    {% if is_following %}
      <a class="btn unfollow" href="javascript:void(0)">Unfollow</a>
    {% else %}
      <!-- <a class="btn icon follow" href="/friend/add/?username={{ username }}">Follow</a> -->
      <a class="btn btn-success follow" href="javascript:void(0)">Follow</a>
    {% endif %}
  {% endifequal %}
{% endblock %}